name: Pull Request Validator
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Run Validator Script
        run: ./.scripts/validators/render.sh

      - name: Check Script Exit Status
        run: exit ${{ steps.validate.outcome == 'success' }}

      - name: Set Pull Request Status
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            :heavy_check_mark: Pull Request Validator passed.

      - name: Prevent Merge on Failure
        if: ${{ steps.validate.outcome != 'success' }}
        run: |
          echo "Error: Pull Request Validator failed. Please fix the issues and try again."
          exit 1

